language: python
python:
  - "3.6"
  - "3.9"
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest coveralls
  - pip install .
script:
  - pytest
after_success:
  - coverage report
  - coveralls
